// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "boilerplate-go/internal/pkg/statements/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// InMemoryRepo is an autogenerated mock type for the InMemoryRepo type
type InMemoryRepo struct {
	mock.Mock
}

// GetByUpload provides a mock function with given fields: uploadID
func (_m *InMemoryRepo) GetByUpload(uploadID string) []entity.Transaction {
	ret := _m.Called(uploadID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUpload")
	}

	var r0 []entity.Transaction
	if rf, ok := ret.Get(0).(func(string) []entity.Transaction); ok {
		r0 = rf(uploadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	return r0
}

// Save provides a mock function with given fields: tx
func (_m *InMemoryRepo) Save(tx entity.Transaction) {
	_m.Called(tx)
}

// NewInMemoryRepo creates a new instance of InMemoryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInMemoryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *InMemoryRepo {
	mock := &InMemoryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
